```{r}
RichardsonDerivative <- function(f, x, h, n = 2) {
  h <- h/2^(0:(n-1))
  res <- (f(x+h)-f(x-h))/(2*h)
  m <- n
  for (i in 2:n) {
    a <- 2^(2*i-2)
    res <- (a*res[2:m]-res[1:(m-1)])/(a-1)
    m <- m - 1
  }
  return(res)
}

MidPointRuleRichardson <- function(f, a, b, n = 2) {
  N <- n
  m <- n
  n <- 2^(0:(n-1))
  res <- sapply(n, function(n) MidPointRule(f, a, b, n))
  for (i in 2:N) {
    a <- 2^(2*i-2)
    res <- (a*res[2:m]-res[1:(m-1)])/(a-1)
    m <- m - 1
  }
  return(res)
}

MidPointRule <- function(f, a, b, n = 1) {
  h <- (b-a)/n
  x <- h*(1:n)
  return(h*sum(f(h*(1:n)+a-h/2)))
}

Hermite <- function(x0, x1, y0, y1, d0, d1) {
 a <- y0
 b <- d0
 h <- x1-x0
 h2 <- h*h
 d <- (h*(d1-d0)-2*(y1-y0)+2*d0*h)/(h*h2)
 c <- (d1-d0-3*d*h2)/(2*h)
 return(c(a,b,c,d))
}

# Vstupem jsou koeficienty (a,b,c,d) a x, pro které počítáme
Horner <- function(coef, x, x0) {
  x <- x-x0
  return(((coef[4]*x+coef[3])*x+coef[2])*x+coef[1])
}

x0 <- pi
x1 <- 2*pi
y0 <- cos(x0)
y1 <- cos(x1)
d0 <- -sin(x0)
d1 <- -sin(x1)

plot(cos, xlim=c(x0, x1), col='red')
x <- seq(x0, x1, 0.001) # navzorkování funkce
lines(x, Horner(Hermite(x0, x1, y0, y1, d0, d1), x, x0), col='blue')
lines(x, Horner(Hermite(x0, x1, y0, y1, -1, d1), x, x0), col='green')
```

```{r}
x <- pi/4
print(cos(x))

RichardsonDerivative(sin, x, h = 0.1, n = 3)
```

```{r}
a <- 0
b <- pi
MidPointRule(sin, a, b, 100)
MidPointRuleRichardson(sin, a, b, n = 2)
```
