-- readonly
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'readonly') THEN
        REVOKE ALL ON SCHEMA Pivonka FROM readonly;
        REVOKE SELECT ON ALL TABLES IN SCHEMA Pivonka FROM readonly;
        ALTER DEFAULT PRIVILEGES IN SCHEMA Pivonka REVOKE SELECT ON TABLES FROM readonly;
    END IF;
END $$;

DROP ROLE IF EXISTS readonly;
DROP USER IF EXISTS honza;

CREATE ROLE readonly;
GRANT USAGE ON SCHEMA Pivonka TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA Pivonka TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA Pivonka GRANT SELECT ON TABLES TO readonly;

CREATE USER honza WITH PASSWORD 'Aa123456';
GRANT readonly TO honza;

-- waiter
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'waiter') THEN
        REVOKE ALL ON SCHEMA Pivonka FROM waiter;
        REVOKE ALL ON ALL TABLES IN SCHEMA Pivonka FROM waiter;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA Pivonka FROM waiter;
        ALTER DEFAULT PRIVILEGES IN SCHEMA Pivonka REVOKE ALL ON TABLES FROM waiter;
    END IF;
END $$;

DROP ROLE IF EXISTS waiter;
DROP USER IF EXISTS petr;

CREATE ROLE waiter;
GRANT USAGE ON SCHEMA Pivonka TO waiter;
GRANT SELECT ON Pivonka.Stoly TO waiter;
GRANT SELECT ON Pivonka.Rezervace TO waiter;
GRANT INSERT ON Pivonka.Objednavky TO waiter;
REVOKE UPDATE, DELETE ON ALL TABLES IN SCHEMA Pivonka FROM waiter;
ALTER DEFAULT PRIVILEGES IN SCHEMA Pivonka REVOKE UPDATE, DELETE ON TABLES FROM waiter;

CREATE USER petr WITH PASSWORD 'Aa123456';
GRANT waiter TO petr;