---
title: "Cviceni4"
author: "Ondřej Švorc"
format: html
editor: visual
---

```{r}
get(load('Stulong.Rdata'))
```

```{r}
# oprava nazvu promennych v souboru
names(Stulong)<-c("ID","vyska","vaha","syst1","syst2","chlst","vino","cukr","bmi",
                  "vek","KOURrisk","Skupina","VekK")
```

```{r}
# aktivace knihovny s popisnymi statistikami
library(DescTools)
```

```{r}
##########################
### Hledani modusu
## Spojita promenna

# pracujte s vyskou jako se spojitou promennou a hledejte modus
vyska <- Stulong$vyska
# histogram - budeme prokladat hustotu, je treba ji tedy uvazovat i na y-ove ose
hist(vyska,col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
     xlab="Vyska v cm",freq=F)
# mozno pouzit i vice sloupcu
hist(vyska,col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
     xlab="Vyska v cm",breaks=15,freq=F)

# prolozime jadrovy odhad hustoty
(jadro <- density(vyska))
lines(jadro,col=2)
# chceme hladsi funkci? musime zmenit bandwidth
(jadro <- density(vyska,bw=3))
lines(jadro,col=4)
  # jaky bandwidth se Vam jevi jako optimalni?

# kde ma odhad hustoty maximum?
jadro$x[which.max(jadro$y)]
```

```{r}
# Najdete modus pro spojitou promennou bmi
# to znamená udělat jádrový odhad (density) a použití which.max a v případě vykreslování grafu freq=F
# PLATÍ PRO SPOJITOU PROMENNOU, NIKOLIV PRO DISKRETNI

bmi <- Stulong$bmi
hist(bmi, col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
     xlab="BMI",breaks=15,freq=F)

# Jádrový odhad
(jadro <- density(bmi,bw=2.5))
lines(jadro,col=4)
```

```{r}
# Nalezený modus
jadro$x[which.max(jadro$y)]
```

```{r}
# pracujte s vahou jako se spojitou promennou a najdete modus
```

```{r}
##############################
### Hledani modusu
## Diskretni promenna s mnoha kategoriemi

# vezmeme nejvyšší sloupec (s nejvyšší pravděpodobností)
# chci, aby byl modus blíže k většímu sloupci (ten, jak končí padesátkou)

# Uvazujme vek jako diskretni promennou
vek <- Stulong$vek
# histogram - nyni muze byt v cetnostech
hist(vek,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Vek v rocich")

# Kolik bude modu? Ve kterem intervalu je modus?
# podle vzorce modus = A + h*d0/(d0+d1)
# A ... dolní mez nejvyššího sloupce
# h ... šířka sloupce
# d0 ... výška nejvyššího sloupce mínus výška sloupce vlevo
# d1 ... výška nejvyššího sloupce mínus výška sloupce vpravo

# plot=F = nevykreslí graf, ale vypíše základní informace o histogramu
hist(vek, plot=F)

meze<-hist(vek, plot=F)$breaks
pocty<-hist(vek, plot=F)$counts

# Kolikaty sloupec je nejvyssi
m<-which.max(pocty)

(A<-meze[m]) # Nejvyšší sloupec začíná od 46 (jeho dolní mez)
(h<-meze[2]-meze[1]) # Nejvyšší sloupec je široký 2 (tedy 46 až 48)
(d0<-pocty[m]-pocty[m-1])
(d1<-pocty[m]-pocty[m+1])
(modus<- A + h*d0/(d0+d1))
```

```{r}
# Urcete modus pro prvni hodnotu systolickeho tlaku (syst1)
tlak <- Stulong$syst1

hist(tlak,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Tlak")

meze<-hist(tlak, plot=F)$breaks
pocty<-hist(tlak, plot=F)$counts

m<-which.max(pocty)

(A<-meze[m]) # Nejvyšší sloupec začíná od 110 (jeho dolní mez)
(h<-meze[2]-meze[1]) # Nejvyšší sloupec je široký 10 (tedy 110 až 120)
(d0<-pocty[m]-pocty[m-1])
(d1<-pocty[m]-pocty[m+1])
(modus<- A + h*d0/(d0+d1))
```

```{r}
# Urcete modus pro cukr
  # pokud sousedni sloupec k tomu nejvyssimu chybi, bere se jeho cetnost jako 0

cukr <- Stulong$cukr

hist(cukr,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Hladina cukru v krvi")

meze<-hist(cukr, plot=F)$breaks
pocty<-hist(cukr, plot=F)$counts

m<-which.max(pocty)

(A<-meze[m]) # Nejvyšší sloupec začíná od 0 (jeho dolní mez)
(h<-meze[2]-meze[1]) 
(d0<-pocty[m] - ifelse(m > 1, pocty[m-1], 0))
(d1 <- pocty[m] - ifelse(m < length(pocty), pocty[m+1], 0))
(modus<- A + h*d0/(d0+d1))
```

```{r}
##########################
## Odlehle hodnoty

# Pro jaké typy rozdělení má smysl odlehlé hodnoty uvažovat?
# - pro jednovrcholové symetrické rozdělení

# Ma promenna vyska odlehle hodnoty
# Je promenna symetricka nebo sesikmena?
# A je jeji rozdeleni jednovrcholove nebo vicevrcholove?
vyska <- Stulong$vyska

# A co na odlehle hodnoty rika boxplot?
hist(vyska,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Vyska v cm",breaks=15)

# Vidime adepty na odlehle hodnoty
# Podle jakeho pravidla boxplot odlehle hodnoty hleda?
boxplot(vyska,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Vyska v cm")

# Zprisnime pravidlo (range=3)
# Do prisnejsiho pravidla se vejdou vsechny hodnoty
boxplot(vyska,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Vyska v cm", range=3)

# IQR = mezikvartalové rozpětí
# - od bližšího kvartilu dál než 1.5*IQR = 1.5*(Q3-Q1)
# - 3*IQR - zvolit pro těžší chvosty

# Jake mame hranice pro odlehle hodnoty?
# 1.5 nasobek mezikvartiloveho rozpeti - adept na odlehle pozorovani
(DM <- quantile(vyska,0.25) - 1.5*IQR(vyska))
vyska[vyska<DM] # odlehlé pozorování - muži, kteří jsou menší než 160 cm
  # dolni adepti na odlehle pozorovani
(HM<-quantile(vyska,0.75) + 1.5*IQR(vyska))
vyska[vyska>HM]
  # horni adepti na odlehle pozorovani

# 3 nasobek mezikvartiloveho rozpeti - odlehla pozorovani
(DM<-quantile(vyska,0.25) - 3*IQR(vyska))
vyska[vyska<DM]
  # dolni odlehla pozorovani
(HM<-quantile(vyska,0.75) + 3*IQR(vyska))
vyska[vyska>HM]
  # horni odlehla pozorovani

# 3 nasobek smerodatne odchylky - adepti na odlehle pozorovani
(DM<-mean(vyska) - 3*sd(vyska))
vyska[vyska<DM]
  # dolni adepti na odlehle pozorovani
(HM<-mean(vyska) + 3*sd(vyska))
vyska[vyska>HM]
  # horni adepti na odlehle pozorovani

# 4 nasobek smerodatne odchylky - odlehle pozorovani
(DM<-mean(vyska) - 4*sd(vyska))
vyska[vyska<DM]
  # dolni odlehla pozorovani
(HM<-mean(vyska) + 4*sd(vyska))
vyska[vyska>HM]
  # horni odlehla pozorovani
```

```{r}
# A jak jsou na tom odlehla pozorovani pro vahu?

vaha <- Stulong$vaha

hist(vaha,col="skyblue",border="darkblue",main="Histogram", ylab="Absolutni cetnosti",
     xlab="Váha v kg", breaks=15)

# Kandidáti na odlehlá pozorování
# Je na nás stanovit správně horní mez (jestli se tam mají ještě zahrnout, nebo ne)
boxplot(vaha,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Váha v kg")

# Range (standardně 1.5) - násobek mezikvartalové rozpětí
boxplot(vaha,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Váha v kg", range=3)

DM1 <- quantile(vaha, 0.25) - 1.5 * IQR(vaha)
HM1 <- quantile(vaha, 0.75) + 1.5 * IQR(vaha)
cat("1.5 * IQR:\n")
cat("Dolní mez DM1:", DM1, "\n")
cat("Hodnoty pod dolní mezí DM1:", vaha[vaha < DM1], "\n")
cat("Horní mez HM1:", HM1, "\n")
cat("Hodnoty nad horní mezí HM1:", vaha[vaha > HM1], "\n\n")

DM2 <- quantile(vaha, 0.25) - 3 * IQR(vaha)
HM2 <- quantile(vaha, 0.75) + 3 * IQR(vaha)
cat("3 * IQR:\n")
cat("Dolní mez DM2:", DM2, "\n")
cat("Hodnoty pod dolní mezí DM2:", vaha[vaha < DM2], "\n")
cat("Horní mez HM2:", HM2, "\n")
cat("Hodnoty nad horní mezí HM2:", vaha[vaha > HM2], "\n\n")

DM3 <- mean(vaha) - 3 * sd(vaha)
HM3 <- mean(vaha) + 3 * sd(vaha)
cat("3 * smerodatna odchylka:\n")
cat("Dolní mez DM3:", DM3, "\n")
cat("Hodnoty pod dolní mezí DM3:", vaha[vaha < DM3], "\n")
cat("Horní mez HM3:", HM3, "\n")
cat("Hodnoty nad horní mezí HM3:", vaha[vaha > HM3], "\n\n")

DM4 <- mean(vaha) - 4 * sd(vaha)
HM4 <- mean(vaha) + 4 * sd(vaha)
cat("4 * smerodatna odchylka:\n")
cat("Dolní mez DM4:", DM4, "\n")
cat("Hodnoty pod dolní mezí DM4:", vaha[vaha < DM4], "\n")
cat("Horní mez HM4:", HM4, "\n")
cat("Hodnoty nad horní mezí HM4:", vaha[vaha > HM4])
```

```{r}
syst <- Stulong$syst1

# POSTUP HLEDÁNÍ ODDLEHLÝCH HODNOT PŘI ASYMETRICKÉM ROZDĚLENÍ
# 1. Potřebujeme provést symetrizující transformaci
#    - první z nich je logaritmus y = ln(x) - funguje jen pro hodnoty >0
#    - tím by se mělo rozdělení symetrizovat (lze vidět na histogramu)
#    - druhá z nich Y = odmocnina z ((xi - min) / (max - min)) - funguje i pro nulu

# zde uz je sesikmeni vyraznejsi (asymetricke), zkusime symetrizujici transformaci
# pro kladna data lze pouzit prirozeny logaritmus
# pro data, kde jsou i zaporne hodnoty, je transformace sqrt((x-min)/(max-min))
hist(syst,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Systolicky tlak")

# pomohlo to? Odlehle hodnoty se hledaji u symetrizovane promenne
ln.syst <- log(syst) # y = ln(x)
hist(ln.syst,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti", xlab="Logaritmus systolickeho tlak")

# krabicovy graf pro puvodni promennou
# pokud chci dosahnout tykadlem na vsechny samostatne body,
#   patricne navysim parametr range
boxplot(syst,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Systolicky tlak")

boxplot(syst,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Systolicky tlak",range=10)

# krabicovy graf pro transformovanou promennou
# mame kandiday na odlehle hodnoty
(DM<-quantile(ln.syst, 0.25) - 1.5*IQR(ln.syst))
(exp(DM))

boxplot(ln.syst,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Logaritmus systolickeho tlaku", range = 3)

```

```{r}
cukr <- Stulong$cukr
# Asymetrické, potřebujeme sesymetrizovat
hist(cukr,col="skyblue",border="darkblue",main="Histogram",ylab="Absolutni cetnosti",
     xlab="Hladina cukru v krvi", breaks = 15)

# Sesymetrizování logaritmem nelze použít, protože cukr může nabývat hodnoty 0
# Použijeme tedy druhý způsob Y = (xi - min) / (max - min)
cukr.t = sqrt((cukr - min(cukr)) / (max(cukr) - min(cukr)))
hist(cukr.t, col="skyblue",border="darkblue",main="Histogram of cukr.t",ylab="Absolutni cetnosti", xlab="Logaritmus hladiny cukru v krvi")
boxplot(cukr.t,col="yellow",border="orange3",main="Krabicovy graf",
        ylab="Hladina cukru v krvi",range=1.5)

DM1 <- quantile(cukr.t, 0.25) - 1.5 * IQR(cukr.t)
HM1 <- quantile(cukr.t, 0.75) + 1.5 * IQR(cukr.t)
cat("1.5 * IQR:\n")
cat("Dolní mez DM1:", DM1, "\n")
cat("Hodnoty pod dolní mezí DM1:", cukr.t[cukr.t < DM1], "\n")
cat("Horní mez HM1:", HM1, "\n")
cat("Hodnoty nad horní mezí HM1:", cukr.t[cukr.t > HM1], "\n\n")

DM2 <- quantile(cukr.t, 0.25) - 3 * IQR(cukr.t)
HM2 <- quantile(cukr.t, 0.75) + 3 * IQR(cukr.t)
cat("3 * IQR:\n")
cat("Dolní mez DM2:", DM2, "\n")
cat("Hodnoty pod dolní mezí DM2:", cukr.t[cukr.t < DM2], "\n")
cat("Horní mez HM2:", HM2, "\n")
cat("Hodnoty nad horní mezí HM2:", cukr.t[cukr.t > HM2], "\n\n")

DM3 <- mean(cukr.t) - 3 * sd(cukr.t)
HM3 <- mean(cukr.t) + 3 * sd(cukr.t)
cat("3 * smerodatna odchylka:\n")
cat("Dolní mez DM3:", DM3, "\n")
cat("Hodnoty pod dolní mezí DM3:", cukr.t[cukr.t < DM3], "\n")
cat("Horní mez HM3:", HM3, "\n")
cat("Hodnoty nad horní mezí HM3:", cukr.t[cukr.t > HM3], "\n\n")

DM4 <- mean(cukr.t) - 4 * sd(cukr.t)
HM4 <- mean(cukr.t) + 4 * sd(cukr.t)
cat("4 * smerodatna odchylka:\n")
cat("Dolní mez DM4:", DM4, "\n")
cat("Hodnoty pod dolní mezí DM4:", cukr.t[cukr.t < DM4], "\n")
cat("Horní mez HM4:", HM4, "\n")
cat("Hodnoty nad horní mezí HM4:", cukr.t[cukr.t > HM4])
```

```{r}
#########################
## Jsou data normalne rozlozena?
# vyska
vyska <- Stulong$vyska
  
# histogram - hodi se ho kreslit v "hustote"
hist(vyska,col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
     xlab="Vyska v cm", freq=F)
  # Ma tvar Gaussovy krivky?
  curve(dnorm(x,mean(vyska),sd(vyska)),from=min(vyska),to=max(vyska), add=T,col=2)
    # prikresleni hustoty odpovidajiciho normalniho rozdeleni 
  
# Sikmost, spicatost
Skew(vyska)
Kurt(vyska)
  # jsou nulove?

# Pravdepodobnostni graf (nejlepší test normality, který momentálně máme)
# kvantil-kvantilový graf
PlotQQ(vyska,pch=19,cex=0.5)
  qqnorm(vyska,pch=19, cex=0.5);qqline(vyska,distribution=qnorm,col=2,lwd=2)
    # graf bez pouziti knihovny DescTools
  # jak cist pravdepodobnostni graf
  # vyska ma priblizne normalni rozdeleni
```

Skew(bmi)

Kurt(bmi)

```{r}
# Ma bmi normalni rozdeleni? Ne, nemá

bmi <- Stulong$bmi
hist(bmi,col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
   xlab="BMI", freq=F)
curve(dnorm(x,mean(bmi),sd(bmi)),from=min(bmi),to=max(bmi), add=T,col=2)

cat("Šikmost:", Skew(bmi),"\n")
cat("Špičatost:", Kurt(bmi),"\n")

PlotQQ(bmi,pch=19,cex=0.5)
qqnorm(bmi,pch=19, cex=0.5);qqline(bmi,distribution=qnorm,col=2,lwd=2)
```

```{r}
# Ma prvni hodnota systolickeho tlaku normalni rozdeleni? Také nemá

tlak <- Stulong$syst1
hist(tlak,col="skyblue",border="darkblue",main="Histogram",ylab="Hustota",
   xlab="Tlak", freq=F)
curve(dnorm(x,mean(tlak),sd(tlak)),from=min(tlak),to=max(tlak), add=T,col=2)

cat("Šikmost:", Skew(tlak),"\n")
cat("Špičatost:", Kurt(tlak),"\n")

PlotQQ(tlak,pch=19,cex=0.5)
qqnorm(tlak,pch=19, cex=0.5);qqline(tlak,distribution=qnorm,col=2,lwd=2)
```
