services:
  # PHP + Apache
  php-apache:
    container_name: project-vps
    build:
      dockerfile: Dockerfiles/PhpApache
    depends_on:
      - database
    volumes:
      - ./www:/var/www  # Mount the full project, not just public/
      - ./www/public:/var/www/html  # Serve only public/
    ports:
      - 8000:80 # Expose Apache on localhost:8000

  # PostgreSQL Database
  database:
    image: postgres:latest
    container_name: project-db
    environment:
      POSTGRES_DB: restaurace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: heslo
    volumes:
      - ./Dockerfiles/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432 # PostgreSQL default port

  # pgAdmin (Database Administration)
  pgadmin:
    image: dpage/pgadmin4
    container_name: project-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5051:80 # Access pgAdmin at http://localhost:5050
    depends_on:
      - database
